name:                normal-forms-converter
version:             0.1.0.0
github:              "Bupaheh/normal-forms-converter"
license:             BSD3
author:              "Bupaheh"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Bupaheh/normal-forms-converter>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  normal-forms-converter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - normal-forms-converter

tests:  
  QuickCheck-test:
    main:                QCTest.hs
    source-dirs:         
    - test/QC
    - test/shared
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - normal-forms-converter
    - QuickCheck
    
  Unit-test:
    main:                UnitTest.hs
    source-dirs:         
    - test/Unit
    - test/shared
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - normal-forms-converter
    - tasty
    - tasty-hunit
